	const_def
	const UNK_OBJ_00 ; $00
	const PARTICLE ; $01
	const UNK_OBJ_02 ; $02
	const UNK_OBJ_03 ; $03
	const UNK_OBJ_04 ; $04
	const UNK_OBJ_05 ; $05
	const UNK_OBJ_06 ; $06
	const UNK_OBJ_07 ; $07
	const UNK_OBJ_08 ; $08
	const UNK_OBJ_09 ; $09
	const UNK_OBJ_0A ; $0a
	const UNK_OBJ_0B ; $0b
	const UNK_OBJ_0C ; $0c
	const UNK_OBJ_0D ; $0d
	const UNK_OBJ_0E ; $0e
	const UNK_OBJ_0F ; $0f
	const UNK_OBJ_10 ; $10
	const UNK_OBJ_11 ; $11
	const UNK_OBJ_12 ; $12
	const UNK_OBJ_13 ; $13
	const UNK_OBJ_14 ; $14
	const UNK_OBJ_15 ; $15
	const UNK_OBJ_16 ; $16
	const UNK_OBJ_17 ; $17
	const UNK_OBJ_18 ; $18
	const UNK_OBJ_19 ; $19
	const UNK_OBJ_1A ; $1a
	const UNK_OBJ_1B ; $1b
	const UNK_OBJ_1C ; $1c
	const UNK_OBJ_1D ; $1d
	const UNK_OBJ_1E ; $1e
	const UNK_OBJ_1F ; $1f
	const UNK_OBJ_20 ; $20
	const UNK_OBJ_21 ; $21
	const UNK_OBJ_22 ; $22
	const UNK_OBJ_23 ; $23
	const UNK_OBJ_24 ; $24
	const UNK_OBJ_25 ; $25
	const UNK_OBJ_26 ; $26
	const UNK_OBJ_27 ; $27
	const UNK_OBJ_28 ; $28
	const UNK_OBJ_29 ; $29
	const UNK_OBJ_2A ; $2a
	const UNK_OBJ_2B ; $2b
	const UNK_OBJ_2C ; $2c
	const UNK_OBJ_2D ; $2d
	const UNK_OBJ_2E ; $2e
	const UNK_OBJ_2F ; $2f
	const UNK_OBJ_30 ; $30
	const UNK_OBJ_31 ; $31
	const UNK_OBJ_32 ; $32
	const UNK_OBJ_33 ; $33
	const UNK_OBJ_34 ; $34
	const UNK_OBJ_35 ; $35
	const UNK_OBJ_36 ; $36
	const UNK_OBJ_37 ; $37
	const UNK_OBJ_38 ; $38
	const UNK_OBJ_39 ; $39
	const UNK_OBJ_3A ; $3a
	const UNK_OBJ_3B ; $3b
	const UNK_OBJ_3C ; $3c
	const UNK_OBJ_3D ; $3d
	const UNK_OBJ_3E ; $3e
	const UNK_OBJ_3F ; $3f
	const UNK_OBJ_40 ; $40
	const UNK_OBJ_41 ; $41
	const UNK_OBJ_42 ; $42
	const UNK_OBJ_43 ; $43
	const UNK_OBJ_44 ; $44
	const UNK_OBJ_45 ; $45
	const UNK_OBJ_46 ; $46
	const UNK_OBJ_47 ; $47
	const UNK_OBJ_48 ; $48
	const UNK_OBJ_49 ; $49
	const UNK_OBJ_4A ; $4a
	const UNK_OBJ_4B ; $4b
	const UNK_OBJ_4C ; $4c
	const UNK_OBJ_4D ; $4d
	const UNK_OBJ_4E ; $4e
	const UNK_OBJ_4F ; $4f
	const UNK_OBJ_50 ; $50
	const UNK_OBJ_51 ; $51
	const UNK_OBJ_52 ; $52
	const UNK_OBJ_53 ; $53
	const UNK_OBJ_54 ; $54
	const UNK_OBJ_55 ; $55
	const UNK_OBJ_56 ; $56
	const UNK_OBJ_57 ; $57
	const UNK_OBJ_58 ; $58
	const UNK_OBJ_59 ; $59
	const UNK_OBJ_5A ; $5a
	const UNK_OBJ_5B ; $5b
	const UNK_OBJ_5C ; $5c
	const UNK_OBJ_5D ; $5d
	const UNK_OBJ_5E ; $5e
	const UNK_OBJ_5F ; $5f
	const UNK_OBJ_60 ; $60
	const UNK_OBJ_61 ; $61
	const UNK_OBJ_62 ; $62
	const UNK_OBJ_63 ; $63
	const UNK_OBJ_64 ; $64
	const UNK_OBJ_65 ; $65
	const UNK_OBJ_66 ; $66
	const UNK_OBJ_67 ; $67
	const UNK_OBJ_68 ; $68
	const UNK_OBJ_69 ; $69
	const UNK_OBJ_6A ; $6a
	const UNK_OBJ_6B ; $6b
	const UNK_OBJ_6C ; $6c
	const UNK_OBJ_6D ; $6d
	const UNK_OBJ_6E ; $6e
	const UNK_OBJ_6F ; $6f
	const UNK_OBJ_70 ; $70
	const UNK_OBJ_71 ; $71
	const UNK_OBJ_72 ; $72
	const UNK_OBJ_73 ; $73
	const UNK_OBJ_74 ; $74
	const UNK_OBJ_75 ; $75
	const UNK_OBJ_76 ; $76
	const UNK_OBJ_77 ; $77
	const UNK_OBJ_78 ; $78
	const UNK_OBJ_79 ; $79
	const UNK_OBJ_7A ; $7a
	const UNK_OBJ_7B ; $7b
	const UNK_OBJ_7C ; $7c
	const UNK_OBJ_7D ; $7d
	const UNK_OBJ_7E ; $7e
	const UNK_OBJ_7F ; $7f
	const UNK_OBJ_80 ; $80
	const UNK_OBJ_81 ; $81
	const UNK_OBJ_82 ; $82
	const UNK_OBJ_83 ; $83
	const UNK_OBJ_84 ; $84
	const UNK_OBJ_85 ; $85
	const UNK_OBJ_86 ; $86
	const UNK_OBJ_87 ; $87
	const UNK_OBJ_88 ; $88
	const UNK_OBJ_89 ; $89
	const UNK_OBJ_8A ; $8a
	const UNK_OBJ_8B ; $8b
	const UNK_OBJ_8C ; $8c
	const UNK_OBJ_8D ; $8d
	const UNK_OBJ_8E ; $8e
	const UNK_OBJ_8F ; $8f
	const UNK_OBJ_90 ; $90
	const UNK_OBJ_91 ; $91
	const UNK_OBJ_92 ; $92
	const UNK_OBJ_93 ; $93
	const UNK_OBJ_94 ; $94
	const UNK_OBJ_95 ; $95
	const UNK_OBJ_96 ; $96
	const UNK_OBJ_97 ; $97
	const UNK_OBJ_98 ; $98
	const UNK_OBJ_99 ; $99
	const UNK_OBJ_9A ; $9a
	const UNK_OBJ_9B ; $9b
	const UNK_OBJ_9C ; $9c
	const UNK_OBJ_9D ; $9d
	const UNK_OBJ_9E ; $9e
	const UNK_OBJ_9F ; $9f
	const UNK_OBJ_A0 ; $a0
	const UNK_OBJ_A1 ; $a1
	const UNK_OBJ_A2 ; $a2
	const UNK_OBJ_A3 ; $a3
	const UNK_OBJ_A4 ; $a4
	const UNK_OBJ_A5 ; $a5
	const UNK_OBJ_A6 ; $a6
	const UNK_OBJ_A7 ; $a7
	const KIRBY_FILE_SELECT ; $a8
	const BOMB_FILE_SELECT ; $a9
	const EXPLOSION_FILE_SELECT ; $aa
	const UNK_OBJ_AB ; $ab
	const UNK_OBJ_AC ; $ac
	const UNK_OBJ_AD ; $ad
	const UNK_OBJ_AE ; $ae
	const UNK_OBJ_AF ; $af
	const UNK_OBJ_B0 ; $b0
	const UNK_OBJ_B1 ; $b1
	const UNK_OBJ_B2 ; $b2
	const UNK_OBJ_B3 ; $b3
	const UNK_OBJ_B4 ; $b4
	const UNK_OBJ_B5 ; $b5
	const UNK_OBJ_B6 ; $b6
	const UNK_OBJ_B7 ; $b7
	const UNK_OBJ_B8 ; $b8
	const UNK_OBJ_B9 ; $b9
	const UNK_OBJ_BA ; $ba
	const UNK_OBJ_BB ; $bb
	const UNK_OBJ_BC ; $bc
	const UNK_OBJ_BD ; $bd
	const UNK_OBJ_BE ; $be
	const UNK_OBJ_BF ; $bf
	const UNK_OBJ_C0 ; $c0
	const UNK_OBJ_C1 ; $c1
	const UNK_OBJ_C2 ; $c2
	const UNK_OBJ_C3 ; $c3
	const UNK_OBJ_C4 ; $c4
	const UNK_OBJ_C5 ; $c5
	const UNK_OBJ_C6 ; $c6
	const UNK_OBJ_C7 ; $c7
	const UNK_OBJ_C8 ; $c8
	const UNK_OBJ_C9 ; $c9
	const UNK_OBJ_CA ; $ca
	const UNK_OBJ_CB ; $cb
	const UNK_OBJ_CC ; $cc
	const UNK_OBJ_CD ; $cd
	const UNK_OBJ_CE ; $ce
	const UNK_OBJ_CF ; $cf
	const UNK_OBJ_D0 ; $d0
	const UNK_OBJ_D1 ; $d1
	const UNK_OBJ_D2 ; $d2
	const UNK_OBJ_D3 ; $d3
	const UNK_OBJ_D4 ; $d4
	const UNK_OBJ_D5 ; $d5
	const UNK_OBJ_D6 ; $d6
	const UNK_OBJ_D7 ; $d7
	const UNK_OBJ_D8 ; $d8
	const UNK_OBJ_D9 ; $d9
	const UNK_OBJ_DA ; $da
	const UNK_OBJ_DB ; $db
	const UNK_OBJ_DC ; $dc
	const UNK_OBJ_DD ; $dd
	const UNK_OBJ_DE ; $de
	const UNK_OBJ_DF ; $df
	const UNK_OBJ_E0 ; $e0
	const UNK_OBJ_E1 ; $e1
	const UNK_OBJ_E2 ; $e2
	const UNK_OBJ_E3 ; $e3
	const UNK_OBJ_E4 ; $e4
	const UNK_OBJ_E5 ; $e5
	const UNK_OBJ_E6 ; $e6
	const UNK_OBJ_E7 ; $e7
	const UNK_OBJ_E8 ; $e8
	const UNK_OBJ_E9 ; $e9
	const UNK_OBJ_EA ; $ea
	const UNK_OBJ_EB ; $eb
	const UNK_OBJ_EC ; $ec
	const UNK_OBJ_ED ; $ed
	const UNK_OBJ_EE ; $ee
	const UNK_OBJ_EF ; $ef
	const UNK_OBJ_F0 ; $f0
	const UNK_OBJ_F1 ; $f1
	const UNK_OBJ_F2 ; $f2
	const UNK_OBJ_F3 ; $f3
	const UNK_OBJ_F4 ; $f4
	const UNK_OBJ_F5 ; $f5
	const UNK_OBJ_F6 ; $f6
	const UNK_OBJ_F7 ; $f7
	const KIRBY_TITLE_SCREEN ; $f8
DEF NUM_OBJECT_TYPES EQU const_value

RSRESET
DEF OBJSTRUCT_UNK00 RB ; $00
DEF OBJSTRUCT_NEXT_OBJ RB ; $01
DEF OBJSTRUCT_PREV_OBJ RB ; $02
DEF OBJSTRUCT_X_POS RB 3 ; $03
DEF OBJSTRUCT_Y_POS RB 3 ; $06
DEF OBJSTRUCT_UNK09 RW ; $09
DEF OBJSTRUCT_UNK0B RW ; $0b
DEF OBJSTRUCT_X_VEL RW ; $0d
DEF OBJSTRUCT_Y_VEL RW ; $0f
DEF OBJSTRUCT_X_ACC RB ; $11
DEF OBJSTRUCT_Y_ACC RB ; $12
DEF OBJSTRUCT_UNK13 RB ; $13
DEF OBJSTRUCT_UNK14 RB ; $14
DEF OBJSTRUCT_FRAME RB ; $15
DEF OBJSTRUCT_OAM_BANK RB ; $16
DEF OBJSTRUCT_OAM_PTR RW ; $17
DEF OBJSTRUCT_UPDATE_FUNC1_BANK RB ; $19
DEF OBJSTRUCT_UPDATE_FUNC1_PTR RW ; $1a
DEF OBJSTRUCT_UPDATE_FUNC2_BANK RB ; $1c
DEF OBJSTRUCT_UPDATE_FUNC2_PTR RW ; $1d
DEF OBJSTRUCT_UNK1F RB ; $1f
DEF OBJSTRUCT_UNK20 RW ; $20
DEF OBJSTRUCT_DRAW_FUNC RW ; $22
DEF OBJSTRUCT_TIMER1 RB ; $24
DEF OBJSTRUCT_TIMER2 RB ; $25
DEF OBJSTRUCT_UNK26 RB ; $26
DEF OBJSTRUCT_VAR   RB ; $27
DEF OBJSTRUCT_STACK_PTR RB ; $28
DEF OBJSTRUCT_UNK29 RB ; $29
DEF OBJSTRUCT_UNK2A RB ; $2a
DEF OBJSTRUCT_UNK2B RB ; $2b
DEF OBJSTRUCT_UNK2C RB ; $2c
DEF OBJSTRUCT_UNK2D RB ; $2d
DEF OBJSTRUCT_UNK2E RB ; $2e
DEF OBJSTRUCT_UNK2F RB ; $2f
DEF OBJSTRUCT_UNK30 RB ; $30
DEF OBJSTRUCT_UNK31 RB ; $31
DEF OBJSTRUCT_UNK32 RB ; $32
DEF OBJSTRUCT_UNK33 RB ; $33
DEF OBJSTRUCT_UNK34 RB ; $34
DEF OBJSTRUCT_UNK35 RB ; $35
DEF OBJSTRUCT_UNK36 RB ; $36
DEF OBJSTRUCT_UNK37 RB ; $37
DEF OBJSTRUCT_UNK38 RB ; $38
DEF OBJSTRUCT_UNK39 RB ; $39
DEF OBJSTRUCT_UNK3A RB ; $3a
DEF OBJSTRUCT_UNK3B RB ; $3b
DEF OBJSTRUCT_UNK3C RB ; $3c
DEF OBJSTRUCT_UNK3D RB ; $3d
DEF OBJSTRUCT_UNK3E RB ; $3e
DEF OBJSTRUCT_UNK3F RB ; $3f
DEF OBJSTRUCT_UNK40 RB ; $40
DEF OBJSTRUCT_UNK41 RB ; $41
DEF OBJSTRUCT_UNK42 RB ; $42
DEF OBJSTRUCT_UNK43 RB ; $43
DEF OBJSTRUCT_UNK44 RB ; $44
DEF OBJSTRUCT_UNK45 RB ; $45
DEF OBJSTRUCT_OAM_TILE_ID RB ; $46
DEF OBJSTRUCT_OAM_FLAGS RB ; $47
DEF OBJSTRUCT_PARENT_OBJ RB ; $48
DEF OBJSTRUCT_UNK49 RB ; $49
DEF OBJSTRUCT_BASE_SCORE RW ; $4a
DEF OBJSTRUCT_UNK4C RB ; $4c
DEF OBJSTRUCT_UNK4D RB ; $4d
DEF OBJSTRUCT_UNK4E RB ; $4e
DEF OBJSTRUCT_UNK4F RB ; $4f
DEF OBJSTRUCT_UNK50 RB ; $50
DEF OBJSTRUCT_UNK51 RB ; $51
DEF OBJSTRUCT_UNK52 RB ; $52
DEF OBJSTRUCT_UNK53 RB ; $53
DEF OBJSTRUCT_UNK54 RB ; $54
DEF OBJSTRUCT_UNK55 RB ; $55
DEF OBJSTRUCT_UNK56 RW ; $56
DEF OBJSTRUCT_UNK58 RW ; $58
DEF OBJSTRUCT_UNK5A RB ; $5a
DEF OBJSTRUCT_UNK5B RB ; $5b
DEF OBJSTRUCT_UNK5C RB ; $5c
DEF OBJSTRUCT_UNK5D RB ; $5d
DEF OBJSTRUCT_UNK5E RB ; $5e
DEF OBJSTRUCT_UNK5F RB ; $5f
DEF OBJSTRUCT_UNK60 RB ; $60
DEF OBJSTRUCT_UNK61 RB ; $61
DEF OBJSTRUCT_UNK62 RB ; $62
DEF OBJSTRUCT_UNK63 RB ; $63
DEF OBJSTRUCT_UNK64 RB ; $64
DEF OBJSTRUCT_UNK65 RW ; $65
DEF OBJSTRUCT_UNK67 RW ; $67
DEF OBJSTRUCT_UNK69 RB ; $69
DEF OBJSTRUCT_UNK6A RW ; $6a
DEF OBJSTRUCT_UNK6C RB ; $6c
DEF OBJSTRUCT_UNK6D RB ; $6d
DEF OBJSTRUCT_UNK6E RB ; $6e
DEF OBJSTRUCT_UNK6F RB ; $6f
DEF OBJSTRUCT_UNK70 RB ; $70
DEF OBJSTRUCT_UNK71 RB ; $71
DEF OBJSTRUCT_UNK72 RB ; $72
DEF OBJSTRUCT_UNK73 RB ; $73
DEF OBJSTRUCT_UNK74 RB ; $74
DEF OBJSTRUCT_UNK75 RB ; $75
DEF OBJSTRUCT_UNK76 RB ; $76
DEF OBJSTRUCT_UNK77 RB ; $77
DEF OBJSTRUCT_UNK78 RB ; $78
DEF OBJSTRUCT_UNK79 RB ; $79
DEF OBJSTRUCT_UNK7A RB ; $7a
DEF OBJSTRUCT_UNK7B RB ; $7b
DEF OBJSTRUCT_UNK7C RB ; $7c
DEF OBJSTRUCT_UNK7D RB ; $7d
DEF OBJSTRUCT_UNK7E RB ; $7e
DEF OBJSTRUCT_UNK7F RB ; $7f
DEF OBJSTRUCT_UNK80 RB ; $80
DEF OBJSTRUCT_UNK81 RB ; $81
DEF OBJSTRUCT_UNK82 RB ; $82
DEF OBJSTRUCT_UNK83 RB ; $83
DEF OBJSTRUCT_UNK84 RB ; $84
DEF OBJSTRUCT_UNK85 RB ; $85
DEF OBJSTRUCT_UNK86 RB ; $86
DEF OBJSTRUCT_UNK87 RB ; $87
DEF OBJSTRUCT_UNK88 RB ; $88
DEF OBJSTRUCT_UNK89 RB ; $89
DEF OBJSTRUCT_UNK8A RB ; $8a
DEF OBJSTRUCT_UNK8B RB ; $8b
DEF OBJSTRUCT_UNK8C RB ; $8c
DEF OBJSTRUCT_UNK8D RB ; $8d
DEF OBJSTRUCT_UNK8E RB ; $8e
DEF OBJSTRUCT_UNK8F RB ; $8f
DEF OBJSTRUCT_UNK90 RB ; $90
DEF OBJSTRUCT_UNK91 RB ; $91
DEF OBJSTRUCT_UNK92 RB ; $92
DEF OBJSTRUCT_UNK93 RB ; $93
DEF OBJSTRUCT_UNK94 RB ; $94
DEF OBJSTRUCT_UNK95 RB ; $95
DEF OBJSTRUCT_UNK96 RB ; $96
DEF OBJSTRUCT_UNK97 RB ; $97
DEF OBJSTRUCT_UNK98 RB ; $98
DEF OBJSTRUCT_UNK99 RB ; $99
DEF OBJSTRUCT_UNK9A RB ; $9a
DEF OBJSTRUCT_UNK9B RB ; $9b
DEF OBJSTRUCT_UNK9C RB ; $9c
DEF OBJSTRUCT_UNK9D RB ; $9d
DEF OBJSTRUCT_UNK9E RB ; $9e
DEF OBJSTRUCT_UNK9F RB ; $9f
DEF OBJSTRUCT_UNKA0 RB ; $a0
DEF OBJSTRUCT_UNKA1 RB ; $a1
DEF OBJSTRUCT_UNKA2 RB ; $a2
DEF OBJSTRUCT_UNKA3 RB ; $a3
DEF OBJSTRUCT_UNKA4 RB ; $a4
DEF OBJSTRUCT_UNKA5 RB ; $a5
DEF OBJSTRUCT_UNKA6 RB ; $a6
DEF OBJSTRUCT_UNKA7 RB ; $a7
DEF OBJSTRUCT_UNKA8 RB ; $a8
DEF OBJSTRUCT_UNKA9 RB ; $a9
DEF OBJSTRUCT_UNKAA RB ; $aa
DEF OBJSTRUCT_UNKAB RB ; $ab
DEF OBJSTRUCT_UNKAC RB ; $ac
DEF OBJSTRUCT_UNKAD RB ; $ad
DEF OBJSTRUCT_UNKAE RB ; $ae
DEF OBJSTRUCT_UNKAF RB ; $af
DEF OBJSTRUCT_UNKB0 RB ; $b0
DEF OBJSTRUCT_UNKB1 RB ; $b1
DEF OBJSTRUCT_UNKB2 RB ; $b2
DEF OBJSTRUCT_UNKB3 RB ; $b3
DEF OBJSTRUCT_UNKB4 RB ; $b4
DEF OBJSTRUCT_UNKB5 RB ; $b5
DEF OBJSTRUCT_UNKB6 RB ; $b6
DEF OBJSTRUCT_UNKB7 RB ; $b7
DEF OBJSTRUCT_UNKB8 RB ; $b8
DEF OBJSTRUCT_UNKB9 RB ; $b9
DEF OBJSTRUCT_UNKBA RB ; $ba
DEF OBJSTRUCT_UNKBB RB ; $bb
DEF OBJSTRUCT_UNKBC RB ; $bc
DEF OBJSTRUCT_UNKBD RB ; $bd
DEF OBJSTRUCT_UNKBE RB ; $be
DEF OBJSTRUCT_UNKBF RB ; $bf
DEF OBJSTRUCT_UNKC0 RB ; $c0
DEF OBJSTRUCT_UNKC1 RB ; $c1
DEF OBJSTRUCT_UNKC2 RB ; $c2
DEF OBJSTRUCT_UNKC3 RB ; $c3
DEF OBJSTRUCT_UNKC4 RB ; $c4
DEF OBJSTRUCT_UNKC5 RB ; $c5
DEF OBJSTRUCT_UNKC6 RB ; $c6
DEF OBJSTRUCT_UNKC7 RB ; $c7
DEF OBJSTRUCT_UNKC8 RB ; $c8
DEF OBJSTRUCT_UNKC9 RB ; $c9
DEF OBJSTRUCT_UNKCA RB ; $ca
DEF OBJSTRUCT_UNKCB RB ; $cb
DEF OBJSTRUCT_UNKCC RB ; $cc
DEF OBJSTRUCT_UNKCD RB ; $cd
DEF OBJSTRUCT_UNKCE RB ; $ce
DEF OBJSTRUCT_UNKCF RB ; $cf
DEF OBJSTRUCT_UNKD0 RB ; $d0
DEF OBJSTRUCT_UNKD1 RB ; $d1
DEF OBJSTRUCT_UNKD2 RB ; $d2
DEF OBJSTRUCT_UNKD3 RB ; $d3
DEF OBJSTRUCT_UNKD4 RB ; $d4
DEF OBJSTRUCT_UNKD5 RB ; $d5
DEF OBJSTRUCT_UNKD6 RB ; $d6
DEF OBJSTRUCT_UNKD7 RB ; $d7
DEF OBJSTRUCT_UNKD8 RB ; $d8
DEF OBJSTRUCT_UNKD9 RB ; $d9
DEF OBJSTRUCT_UNKDA RB ; $da
DEF OBJSTRUCT_UNKDB RB ; $db
DEF OBJSTRUCT_UNKDC RB ; $dc
DEF OBJSTRUCT_UNKDD RB ; $dd
DEF OBJSTRUCT_UNKDE RB ; $de
DEF OBJSTRUCT_UNKDF RB ; $df
DEF OBJSTRUCT_UNKE0 RB ; $e0
DEF OBJSTRUCT_UNKE1 RB ; $e1
DEF OBJSTRUCT_UNKE2 RB ; $e2
DEF OBJSTRUCT_UNKE3 RB ; $e3
DEF OBJSTRUCT_UNKE4 RB ; $e4
DEF OBJSTRUCT_UNKE5 RB ; $e5
DEF OBJSTRUCT_UNKE6 RB ; $e6
DEF OBJSTRUCT_UNKE7 RB ; $e7
DEF OBJSTRUCT_UNKE8 RB ; $e8
DEF OBJSTRUCT_UNKE9 RB ; $e9
DEF OBJSTRUCT_UNKEA RB ; $ea
DEF OBJSTRUCT_UNKEB RB ; $eb
DEF OBJSTRUCT_UNKEC RB ; $ec
DEF OBJSTRUCT_UNKED RB ; $ed
DEF OBJSTRUCT_UNKEE RB ; $ee
DEF OBJSTRUCT_UNKEF RB ; $ef
DEF OBJSTRUCT_UNKF0 RB ; $f0
DEF OBJSTRUCT_UNKF1 RB ; $f1
DEF OBJSTRUCT_UNKF2 RB ; $f2
DEF OBJSTRUCT_UNKF3 RB ; $f3
DEF OBJSTRUCT_UNKF4 RB ; $f4
DEF OBJSTRUCT_UNKF5 RB ; $f5
DEF OBJSTRUCT_UNKF6 RB ; $f6
DEF OBJSTRUCT_UNKF7 RB ; $f7
DEF OBJSTRUCT_UNKF8 RB ; $f8
DEF OBJSTRUCT_UNKF9 RB ; $f9
DEF OBJSTRUCT_UNKFA RB ; $fa
DEF OBJSTRUCT_UNKFB RB ; $fb
DEF OBJSTRUCT_UNKFC RB ; $fc
DEF OBJSTRUCT_UNKFD RB ; $fd
DEF OBJSTRUCT_UNKFE RB ; $fe
DEF OBJSTRUCT_UNKFF RB ; $ff

	const_def
	const PARTICLE_00
	const PARTICLE_01
	const PARTICLE_02
	const PARTICLE_03
	const PARTICLE_04
	const PARTICLE_05
	const PARTICLE_06
	const PARTICLE_07
	const PARTICLE_08
	const PARTICLE_09
	const PARTICLE_0A
	const PARTICLE_0B
	const PARTICLE_0C
	const PARTICLE_0D
	const PARTICLE_0E
	const PARTICLE_0F
	const PARTICLE_10
	const PARTICLE_11
	const PARTICLE_12
	const PARTICLE_13
	const PARTICLE_14
	const PARTICLE_15
DEF NUM_PARTICLES EQU const_value
