INCLUDE "constants/hardware.inc"

INCLUDE "macros/constants.asm"
INCLUDE "macros/asserts.asm"
INCLUDE "macros/code.asm"
INCLUDE "macros/data.asm"

INCLUDE "constants/audio_constants.asm"
INCLUDE "constants/gfx_constants.asm"
INCLUDE "constants/kirby_constants.asm"
INCLUDE "constants/level_constants.asm"
INCLUDE "constants/menu_constants.asm"
INCLUDE "constants/misc_constants.asm"
INCLUDE "constants/object_constants.asm"
INCLUDE "constants/sgb_constants.asm"
INCLUDE "constants/sound_constants.asm"

INCLUDE "macros/audio_commands.asm"
INCLUDE "macros/coords.asm"
INCLUDE "macros/level.asm"
INCLUDE "macros/script.asm"
INCLUDE "macros/sgb.asm"
INCLUDE "macros/ram.asm"
